### ISSUE TITLE
Unable to start ntopng 3.1.171016-3574 on rasberry pi 2b running jessie_pi

### ISSUE THREAD

**Issue by jasonamorrow** [ntop/ntopng#1531]
After running the latest update from /RaspberryPI/jessie_pi/armhf ntopng fails to start:

Setting up nprobe (8.1.171016-5920) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
Executing /usr/sbin/update-rc.d nprobe enable
(Re)Starting nprobe...
Stopping nProbe wlan0
Making the /var/log/nprobe directory...
Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 6
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mdelavaud** [comment]
Try to update pf-ring aswell, if you have the latest version installed then check that the pf_ring service is enabled and running

**Comment by jasonamorrow** [comment]
@mdelavaud pf_ring isn't in the /RaspberryPI/jessie_pi/ repo and I don't believe it was needed prior to the update.

**Comment by simonemainardi** [comment]
duplicate of #1528

**Comment by simonemainardi** [comment]
please, try to `apt-get update && apt-get install ntopng`  now

**Comment by jasonamorrow** [comment]
@simonemainardi I get the same result:

sudo apt install ntopng
Reading package lists... Done
Building dependency tree
Reading state information... Done
ntopng is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 6
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

Could it be something with nprobe? I get the following when trying to start it:

sudo service nprobe start
Failed to start nprobe.service: Unit pf_ring.service failed to load: No such file or directory

**Comment by emanuele-f** [comment]
Please run `apt-get update` and `apt-get install ntopng` again. The user on #1528 reported it is fixed now

**Comment by simonemainardi** [comment]
we are migrating rpi builds to stretch so please make sure to updte as armnf jessie will be discontinued

**Comment by jasonamorrow** [comment]
Looks like they have already been discontinued:
W: Failed to fetch http://apt.ntop.org/jessie_pi/armhf/Packages  404  Not Found

W: Failed to fetch http://apt.ntop.org/jessie_pi/all/Packages  404  Not Found

The upgrade from jessie to stretch isn't a simple in place upgrade. It will be some time before I can migrate.

**Comment by jasonamorrow** [comment]
@simonemainardi after migrating to stretch ntopng was able start, but I still get the following from nprobe:

Setting up nprobe (8.1.171031-5937) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state of nprobe.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nprobe
insserv: Service pf_ring has to be enabled to start service nprobe
insserv: Service cluster has to be enabled to start service nprobe
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for man-db (2.7.6.1-2) ...
Setting up ntopng-data (3.1.171031) ...
Errors were encountered while processing:
 nprobe
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by simonemainardi** [comment]
please use the nProbe tracker as this seems related to nProbe.
