### ISSUE TITLE
dashboard not working with "many interfaces" view

### ISSUE THREAD

**Issue by QuentinBibas** [ntop/ntopng#1717]
Hi,

so, context :
i'm trying to monitor an ESX farm consisting of 12 hosts.
each host was deployed with a small ntopng VM mainly for probing, and some direct access in case it's needed (community ed)

each VM send its results to a main central ntopng server
the server also monitor a physical network TAP on 2 of its 1Gb NIC
the server conf file looks like this :

`````
##########################
# fichier de conf NTOPNG # 
##########################
-d=/var/tmp/ntopng
-G=/var/run/ntopng.pid

###########################################
# liste des interfaces réseaux monitorées # 
###########################################
# lien local / interface web 
-i=bond0.218

# TAP RSX ASA #
-i=eno3
-i=eno4
-i="view:eno3,eno4"


# ESXMON-TEST #
-i="tcp://10.179.218.164:5556"

# cluster ESX AMD #
-i="tcp://10.179.218.165:5556"
-i="tcp://10.179.218.166:5556"
-i="tcp://10.179.218.167:5556"
-i="tcp://10.179.218.168:5556"
-i="tcp://10.179.218.169:5556"
-i="tcp://10.179.218.170:5556"
-i="tcp://10.179.218.171:5556"
-i="tcp://10.179.218.172:5556"
-i="tcp://10.179.218.173:5556"
-i="tcp://10.179.218.174:5556"
-i="tcp://10.179.218.175:5556"
-i="tcp://10.179.218.176:5556"
# **next line got cut a bit from the copy/paste action.**
# **It should have 12 interfaces, the ones listed above**
-i="view:tcp://10.179.218.165:5556,tcp://10.179.218.166:5556,tcp://10.179.218.167:5556,tcp://10.179.218.168:5556,tcp://10.179.218.169:5556,tcp://10.179.218.170:5556,tcp://10.179.218.171:555$
#-i="tcp://10.179.218.165:5556,tcp://10.179.218.166:5556"

#######################################
# Addresse d'accès de l'interface web # 
#######################################
-w=10.179.218.121:80

##################################
# plage(s) d'addresses locale(s) #
##################################
#-m=10.179.0.0/16
-m=10.179.0.0/16

###############################################
# comportement du DNS : # 
###############################################
-n=1

########################################
# association avec une base type MySQL # 
########################################
-F "mysql;localhost;ntopng;flows;XXXXXX;XXXXXX"

##########
# divers # 
##########
#--online-license-check
-p="/etc/ntopng/protosAPHP"
`````

the view:eno3,eno4 works fine
the other one doesn't display in the dashboard
(i mean, if you select it then switch to the dashboard, ntopng selects an other interface)

edit
i've tested both with and witout view:
when using the view: toggle, the eno3,eno4 one has some trouble loading a dashboard but finally does at the 3rd or 4th attempt.
when not using the view toggle, that same interface has no problem loading into the dashboard.
the other "interface" with all 12 childs attached, doesn't load into dashboard with any of the writings

ie doing
-i="view:eno3,eno4"
or
-i=eno3,eno4

The thing i want to achieve is this :
Being able to watch each of the 12 interfaces on the left view (the "by interface" view"), while watching the total per protocol traffic on all interfaces at once
PS : is there a way to affect several interfaces to a user ?

**Comment by QuentinBibas** [comment]
the view interface that doesn't work in the dashboard seems to be properly recognized by ntopng :
![image](https://user-images.githubusercontent.com/34896282/37966641-71aad506-31c9-11e8-8b4b-8d72cd1c37ac.png)


![image](https://user-images.githubusercontent.com/34896282/37966608-5973aa80-31c9-11e8-8597-018639851340.png)

**Comment by QuentinBibas** [comment]
no answer in 7 days

is what i want to achieve possible ?
is there an other way to have the same result ?

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue was due to the very long interface name used for the view and is now fixed. We have also better handled long interface names also in the web interface.

Changes will be available in the next ntopng dev build.

**Comment by QuentinBibas** [comment]
thanks

ETA for the patch on stable ?

**Comment by simonemainardi** [comment]
1 week

**Comment by QuentinBibas** [comment]
update :

Still not working ATM, ntopng Enterprise Edition v.3.2.180410

![image](https://user-images.githubusercontent.com/34896282/38671130-d6fcdcfa-3e4a-11e8-9b96-67441d9df595.png)

whenever i exit this screen to get to the dashboard or even the Flows screen, another interface is selected (and the data is also from the other interface)

**Comment by simonemainardi** [comment]
release is not out yet. hold on a couple of days.

**Comment by QuentinBibas** [comment]
what version number should I be expecting (if already known) ?

**Comment by emanuele-f** [comment]
I should be `3.2.2`
