### ISSUE TITLE
Traffic Report page no response

### ISSUE THREAD

**Issue by HoseinKashefi** [ntop/ntopng#2198]
Hi
when I try to select report duration from 1w or more , ntopng goes to waiting state and no response.
cento --version
v.1.5.181119
ntopng --version
v.3.7.181119

**Comment by emanuele-f** [comment]
Hi, are you using InfluxDB or RRD as the timeseries storage (RRD is the default). Do you see any errors in the ntopng log? Please check out `sudo journalctl -u ntopng`. Can you post a screenshot of your ntopng "runtime status" page (under the home icon)?

**Comment by HoseinKashefi** [comment]
I use RRD format,
here you can find some journal output : 
Dec 04 15:17:10  ntopng[4040]: We trust you have received the usual lecture from the local System
Dec 04 15:17:10  ntopng[4040]: Administrator. It usually boils down to these three things:
Dec 04 15:17:10  ntopng[4040]: #1) Respect the privacy of others.
Dec 04 15:17:10  ntopng[4040]: #2) Think before you type.
Dec 04 15:17:10  ntopng[4040]: #3) With great power comes great responsibility.
Dec 04 15:17:10  sudo[8884]: pam_unix(sudo:auth): conversation failed
Dec 04 15:17:10  ntopng[4040]: sudo: no tty present and no askpass program specified
Dec 04 15:17:10  sudo[8884]: pam_unix(sudo:auth): auth could not identify password for [ntopng]
Dec 04 15:17:10  sudo[8884]: pam_succeed_if(sudo:auth): requirement "uid >= 1000" not met by user "ntopng"
Dec 04 15:17:12  sudo[8884]:   ntopng : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/n2diskctl is-active
Dec 04 15:17:12  ntopng[4040]: We trust you have received the usual lecture from the local System
Dec 04 15:17:12  ntopng[4040]: Administrator. It usually boils down to these three things:
Dec 04 15:17:12  ntopng[4040]: #1) Respect the privacy of others.
Dec 04 15:17:12  ntopng[4040]: #2) Think before you type.
Dec 04 15:17:12  ntopng[4040]: #3) With great power comes great responsibility.
Dec 04 15:17:12  sudo[8885]: pam_unix(sudo:auth): conversation failed
Dec 04 15:17:12  ntopng[4040]: sudo: no tty present and no askpass program specified
Dec 04 15:17:12  sudo[8885]: pam_unix(sudo:auth): auth could not identify password for [ntopng]
Dec 04 15:17:12  sudo[8885]: pam_succeed_if(sudo:auth): requirement "uid >= 1000" not met by user "ntopng"
Dec 04 15:17:14  sudo[8885]:   ntopng : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/local/bin/n2diskctl is-active

![ntop-runtime](https://user-images.githubusercontent.com/43135531/49496286-c6371f80-f87a-11e8-9ade-56b1a0892d28.jpg)

**Comment by lucaderi** [comment]
@emanuele-f  @cardigliano The bug is that ntopng should NOT start tools that are not necessary such as this n2diskctl is-active and in particular with sudo. Please fix this behaviour ASAP as it can lead to security issues.

**Comment by lucaderi** [comment]
@HoseinKashefi These tools are old. Please upgrade and the issue should disappear.

**Comment by emanuele-f** [comment]
@HoseinKashefi the ntopctl command issue should be fixed with the new version of ntopng. Please check this out and open a new bug if not. Regarding the report, due to a bug daily samples were not written so the raw samples are used instead and, since there are really a lot of points, the page blocks. Please wait for the daily script to run correctly at midnight in order to fix the problem.

**Comment by lucaderi** [comment]
This #2204 needs to be implemented to harden ntopng further

**Comment by HoseinKashefi** [comment]
Dear Emanuele and Luca
Thank you very much.
I will upgrade ASAP.

**Comment by HoseinKashefi** [comment]
it was updated and issue still exist, here some log after ntopng running : 

Dec 05 18:06:18  sudo[22236]:   ntopng : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/ntopctl n2n has-service n2n_assistance
Dec 05 18:06:18  sudo[22241]:   ntopng : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/ntopctl n2disk has-service tcp://*:5556c
Dec 05 18:06:18  ntopng[22201]: 05/Dec/2018 18:06:18 [PeriodicActivities.cpp:109] Each periodic activity script will use 2 threads
Dec 05 18:06:18  ntopng[22201]: 05/Dec/2018 18:06:18 [NetworkInterface.cpp:2595] Started packet polling on interface tcp://*:5556c [id: 0]
Dec 05 18:06:19  ntopng[22201]: 05/Dec/2018 18:06:19 [CollectorInterface.cpp:122] Collecting flows on tcp://*:5556c
Dec 05 18:07:00  ntopng[22201]: [LuaEngine.cpp:8243] WARNING: Script failure module 'minute' not found:
Dec 05 18:07:00  ntopng[22201]: 05/Dec/2018 18:07:00 [LuaEngine.cpp:8243] WARNING: Script failure module 'minute' not found:
Dec 05 18:08:00  ntopng[22201]: [LuaEngine.cpp:8243] WARNING: Script failure module 'minute' not found:
Dec 05 18:08:00  ntopng[22201]: 05/Dec/2018 18:08:00 [LuaEngine.cpp:8243] WARNING: Script failure module 'minute' not found:

**Comment by emanuele-f** [comment]
Do you still see the `command not allowed` error in the logs? If not, then this should be fixed. About the minute.lua, I've just commited a fix, anyway it won't create issues.

**Comment by HoseinKashefi** [comment]
I've checked it again, after restarting service, it's worked properly.
thank you

**Comment by emanuele-f** [comment]
Thank you for reporting
