### ISSUE TITLE
The "Top Senders" and "Top Receivers" are not appeared in the specific interface when I used "Dynamic Traffic Disaggregation".

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#5832]
Hello,

I upgrade to  the ntopng Enterprise L v.5.0.210901 (Ubuntu 20.04.2 LTS).   
Some interfaces show the "Top Senders" and "Top Receivers" but  small traffic interfaces are not.
Those interfaces are set by the "Dynamic Traffic Disaggregation".

I have collected the information what I think that the ntop team needs to investigate this problem.

[Attached file]
"ntopng screen" direcoty ・・・ I put screenshots both no problem ones and problems ones.
"URL" direcotry ・・・  it includes the list of URL regarding the ""ntopng screen" direcoty.
"conf" directory ・・・ it includes the "configuration.json".
"bundle-tools" ・・・　various files for investigation like syslog , ntopng.conf, nprobe.conf and dmesg... etc.

[top sender and receiver no showing.zip](https://github.com/ntop/ntopng/files/7097483/top.sender.and.receiver.no.showing.zip)

If needed more information kindly tell me.

regards,

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp could you please try a longer time frame? for example 1d, to check if still those information are not present

**Comment by Yoshihiro-jp** [comment]
I see. tomorrow I would do it  in my company and then let's you know the result.

**Comment by Yoshihiro-jp** [comment]
> Hi @Yoshihiro-jp could you please try a longer time frame? for example 1d, to check if still those information are not present

I see. tomorrow I would do it in my company and then let's you know the result

**Comment by Yoshihiro-jp** [comment]
> Hi @Yoshihiro-jp could you please try a longer time frame? for example 1d, to check if still those information are not present

Dear @MatteoBiscosi ,
I checked a longer time frame but the result was the same. 
Could I do something for the ntop team to resolve this problem?

![1d c800 IF0](https://user-images.githubusercontent.com/58843707/131931620-6a29fa76-e558-41b9-a525-afa938ebcc2a.PNG)
![1M c800 IF0](https://user-images.githubusercontent.com/58843707/131931622-118fa33f-7d31-4b98-bbe2-bc9ab603bb9c.PNG)
![1w c800 IF0](https://user-images.githubusercontent.com/58843707/131931625-c7accaf8-e505-41a6-9aaa-8c9cabbc95ad.PNG)
![1y c800 IF0](https://user-images.githubusercontent.com/58843707/131931628-3f84898e-e7bd-4345-bdb0-1da1464eeebe.PNG)

**Comment by simonemainardi** [comment]
Are you sure there is traffic available for those interfaces? You can check simply by picking the "Traffic" timeseries from the dropdown. You have to have continuous traffic to make sure timeseries get generated properly.

**Comment by Yoshihiro-jp** [comment]
> Are you sure there is traffic available for those interfaces? You can check simply by picking the "Traffic" timeseries from the dropdown. You have to have continuous traffic to make sure timeseries get generated properly.

Yes I am sure.In the traffic timeseries it has the traffic like attached files(only ICMP).

regards,
Yoshihiro
[top an receiver problems traffic.zip](https://github.com/ntop/ntopng/files/7118121/top.an.receiver.problems.traffic.zip)

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp I'm sorry for the late response, however now the problem should be fixed, in the specific case the graph is going to show the Top LOCAL Senders/Receivers (Before there was a missleading description) so probably, in your case, you don't have local hosts with significant traffic; instead the table below is an all round Top Senders/Receivers, so there are both local and remote hosts. An update should be available in a few hours please let me know if, after the update, you see the table filled (you need at least 30min/1hour of data) or not.

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi , 
Thank you for your response. 
I upgrade to below version.

ntop@ntopng:/etc/ntopng$ sudo ntopng -V
Version:        5.0.210908 [Enterprise/Professional build]
GIT rev:        5.0-stable:a0c7909ee6e4fc67ce3542a8e5c41ea5898a6554:20210908

Unfortunately it looks like that the problem is still remaining even if I waited more than 1 hours.
Kindly refer to the attached files.
![1hour top senders](https://user-images.githubusercontent.com/58843707/132644803-a7d05373-f867-4ed3-99bb-0a2df6b15642.png)
![1hour traffic](https://user-images.githubusercontent.com/58843707/132644810-02cd9c17-9993-4a6d-850a-feb34262f964.png)

And as you can see the interface has both local and remote host.

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp sorry for the trouble, it was my bad, I didn't see that you have Stable version and fixed only dev version. Now I should have fixed into the stable version too. New builds are going to start soon, please let me know and sorry again for the error

**Comment by Yoshihiro-jp** [comment]
> Hi @Yoshihiro-jp sorry for the trouble, it was my bad, I didn't see that you have Stable version and fixed only dev version. Now I should have fixed into the stable version too. New builds are going to start soon, please let me know and sorry again for the error

Dear  @MatteoBiscosi ,

Kindly refer to the attached file.
I upgraded to the below stable version.

ntop@ntopng:/etc/ntopng$ sudo ntopng -V
Version:        5.0.210920 [Enterprise/Professional build]
GIT rev:        5.0-stable:fd6465bdbeda14d2f8ed420c72abe47d3b9b7afb:20210920
Pro rev:        r4196
Built on:       Ubuntu 20.04.3 LTS

I noticed that you implemented the Top Local senders and Top Local Receivers.
I tested it again but only particular Interface is still not showing the graph.
Kindly refer to the attached file.
As you can see those hosts are local hosts.
And my settings is below.

/etc/ntopng/ntopng.conf
-m=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8

Could I do something to resolve this problem?


regards,
Yoshihihro




[still problems20210921.zip](https://github.com/ntop/ntopng/files/7201556/still.problems20210921.zip)

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp , did you perhaps enabled the option set the local broadcast domain as MAC address on that interface?
![Screenshot from 2021-09-22 12-26-25](https://user-images.githubusercontent.com/49585191/134327630-9b5b6184-9297-44df-91e2-4619ff28d05a.png)
Could you please send me the http request to get the graph and the response (see the picture below, the request is called "ts.lua")? I'm sorry to ask all this question but I'm not able to reproduce this behavior in my lab so I'm trying to gather all the usefull information.
![Screenshot from 2021-09-22 12-28-16](https://user-images.githubusercontent.com/49585191/134327967-15bce77f-f711-4fb3-ab58-276cd96b8840.png)
If you have sensible information there please drop an email with the info I requested to: biscosi at ntop.org

**Comment by Yoshihiro-jp** [comment]
[ntopng Top Local senders_receivers bug.zip](https://github.com/ntop/ntopng/files/7209960/ntopng.Top.Local.senders_receivers.bug.zip)

Dear @MatteoBiscosi ,

> did you perhaps enabled the option set the local broadcast domain as MAC address on that interface?

Kindly refer to the attached file. I set it with "IP Address".

>Could you please send me the http request to get the graph and the response (see the picture below, the request is called >"ts.lua")? 

Kindly refer to the attached file. 
It is like below.
https://192.168.91.50/lua/rest/v2/get/timeseries/ts.lua?ts_query=ifid%3A5&initial_point=true&epoch_end=1632306900&epoch_begin=1632305100&zoom=30m&ts_schema=top%3Alocal_receivers&ts_compare=30m&limit=6

If there are any lack of information kindly tell me.

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp i did a greater fix to the top senders/receivers table because there was a big aggregating the stats. In a few hours a new update should be available, please update and let me know if everything is fine.
I'm still unable to reproduce your problem. Which type of dynamic traffic disaggregation do you have? However as you can see from the screenshot you gave me, no data is present into the table (Column Received), so probably there is a problem there.

Please send me the answer of 'ts.lua' request and 'get_ts_table.lua' request (screenshot below)
![Screenshot from 2021-09-24 11-38-30](https://user-images.githubusercontent.com/49585191/134653680-36089b2a-a17e-4120-86b4-a7f219b7f611.png)

**Comment by Yoshihiro-jp** [comment]
> Hi @Yoshihiro-jp i did a greater fix to the top senders/receivers table because there was a big aggregating the stats. In a few hours a new update should be available, please update and let me know if everything is fine.

Dear @MatteoBiscosi ,
I upgrade to the "Ver. 5.0.210923" and I had waited for a hour then I checked the Top Local Senders/Receivers graphs.
Like attached file the problem is still remaining. 

> I'm still unable to reproduce your problem. Which type of dynamic traffic disaggregation do you have? 

I use  the "Probe IP + Ingress Interface".

> Please send me the answer of 'ts.lua' request and 'get_ts_table.lua' request (screenshot below)
> ![Screenshot from 2021-09-24 11-38-30](https://user-images.githubusercontent.com/49585191/134653680-36089b2a-a17e-4120-86b4-a7f219b7f611.png)

Kindly refer to the "Readme(version 5.0.210923).txt". I collected those response, Headers and Request.

By the way if you can't reproduce the problem I could provide you to access my ntopng server.
I have the experience before I did it with Alfredo in your team.
Kindly think about it.

regards,
[ntopng bug 20210925.zip](https://github.com/ntop/ntopng/files/7228747/ntopng.bug.20210925.zip)

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp , I fixed the problem of the empty data into the sent/rcvd column of the table but I'm still unable to reproduce the empty timeseries of the local hosts, infact as you can see from my screenshot I added 2 local hosts by using -m options and I have them into the timeseries charts.
![Screenshot from 2021-09-27 11-13-47](https://user-images.githubusercontent.com/49585191/134880250-f585d7d9-8d34-4bf8-be0a-91454c514c12.png)

So if possible, if you could provide the access to your ntopng would be great.

**Comment by MatteoBiscosi** [comment]
Verified as Fixed. Please reopen this ticket if a new problem of this type arise
