### ISSUE TITLE
Can't delete a sub-interface + Multi crash of ntopng

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5984]
Hello,

-------------
EDIT: **This problem cause a lots of error and crash of ntopng**, I receive 4 mails per minute:

`[15/10/2021 13:23:15] [Error] [Process][System][ntopng] Started after anomalous termination (bug report) ntopng v.5.1.211013 (15701) [OS: Debian GNU/Linux 10 (buster)][pid: 15912][options: --interface "eno2" --interface "enp8s0f0" --interface "enp8s0f1" --https-port "3000" --http-port "3001" --ndpi-protocols "/var/lib/ntopng/protos.txt" --max-num-flows "524288" ] `

------------

The problem now is I can not delete a sub interface manually, the button "delete" not validate the command.
![image](https://user-images.githubusercontent.com/86605223/137467806-73e5b33e-2de5-48b7-ab0b-2a5890bc833c.png)

I've checked on an other sub-interface, and a message exit when I can delete it.

Any idea ?

Is it possible to use the API to delete a sub-interface in CLI ?

**Comment by thomasbruchet** [comment]
IThe sub interface that have this problem was created this morning.
I've named them like that: VLAN_name(VLAN_ID)
I've deleted all the old sub interface that was just named like "VLAN_name" withtout the "(xxx)"
I've created again a new interface withtout (xxx) and try to delete them, that work.

I think the (xxx) create a bug in the generation of the interface but can't even delete them.
Here is the popup that appear when I can delete the sub-interface
![image](https://user-images.githubusercontent.com/86605223/137481630-bbdc9cd1-013f-4855-9c98-4643b1457891.png)

**Comment by MatteoBiscosi** [comment]
Hi @thomasbruchet I've test it on my machine but everything seems working fine. Could you please share your `ntopng --version`? After that please open the developing tools of your web browser (in my case i just need to click `f12` or right click on the browser -> `developer tools` or `inspect`) and let me know if some kind of error appears into the console tab other then the two in my screenshot. After that please check if there is some error in your ntopng (on my ubuntu i run the `systemctl status ntopng` or just use the journal, `journalctl -e -u ntopng`) 

![Screenshot from 2021-10-15 15-50-48](https://user-images.githubusercontent.com/49585191/137498451-1f9ad544-040d-4348-8cc2-b74fc933b0aa.png)

**Comment by thomasbruchet** [comment]
Hello;
> ntopng --version
```
Version:        5.1.211013 [Enterprise/Professional build]
GIT rev:        dev:b9e0f1f3549bb08d4090aa2d5dd0bbce7123d82f:20211013
Pro rev:        r4270
Built on:       Debian GNU/Linux 10 (buster)
System Id:      L5404F99DB206AB13--U5404F99DA6F71083--OL
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Sat May 14 16:07:24 2022 [211 days left]
```
> sudo systemctl status ntopng 
```
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-10-15 15:54:40 CEST; 5s ago
  Process: 46054 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a r
  Process: 46068 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 46070 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exite
  Process: 46072 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /ru
 Main PID: 46074 (ntopng)
    Tasks: 15 (limit: 7372)
   Memory: 205.2M
   CGroup: /system.slice/ntopng.service
           └─46074 /usr/bin/ntopng /run/ntopng.conf

oct. 15 15:54:42 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:42 [Ntop.cpp:3286] Added Local Network fe80::210:18ff:fef3:d28/64
oct. 15 15:54:42 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:42 [Ntop.cpp:937] Adding fe80::210:18ff:fef3:d2a/128 as IPv6 interface address
oct. 15 15:54:42 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:42 [Ntop.cpp:947] Adding fe80::210:18ff:fef3:d2a/64 as IPv6 local network for
oct. 15 15:54:42 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:42 [Ntop.cpp:3286] Added Local Network fe80::210:18ff:fef3:d2a/64
oct. 15 15:54:42 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:42 [Ntop.cpp:937] Adding fe80::46a8:42ff:fe01:f39c/128 as IPv6 interface addre
oct. 15 15:54:42 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:42 [Ntop.cpp:947] Adding fe80::46a8:42ff:fe01:f39c/64 as IPv6 local network fo
oct. 15 15:54:42 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:42 [Ntop.cpp:3286] Added Local Network fe80::46a8:42ff:fe01:f39c/64
oct. 15 15:54:43 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:43 [PeriodicActivities.cpp:107] Started periodic activities loop...
oct. 15 15:54:44 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:44 [startup.lua:37] Processing startup.lua: please hold on...
oct. 15 15:54:44 MCONSPP01 ntopng[46074]: 15/Oct/2021 15:54:44 [startup.lua:169] [lists_utils.lua:784] Refreshing category lists...
```

I've redone the same thing 2mn later:
> sudo systemctl status ntopng 
```
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Fri 2021-10-15 15:55:44 CEST; 3s ago
  Process: 46804 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a r
  Process: 46818 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 46820 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exite
  Process: 46822 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /ru
  Process: 46824 ExecStart=/usr/bin/ntopng /run/ntopng.conf (code=killed, signal=SEGV)
  Process: 46973 ExecStopPost=/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid (code=exited, status=0/SUCCESS)
 Main PID: 46824 (code=killed, signal=SEGV)
lines 1-10/10 (END)
```

> sudo journalctl -e -u ntopng
```
oct. 15 15:57:28 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:28 [Ntop.cpp:947] Adding fe80::46a8:42ff:fe01:f39c/64 as IPv6 local network fo
oct. 15 15:57:28 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:28 [Ntop.cpp:3286] Added Local Network fe80::46a8:42ff:fe01:f39c/64
oct. 15 15:57:28 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:28 [PeriodicActivities.cpp:107] Started periodic activities loop...
oct. 15 15:57:29 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:29 [startup.lua:37] Processing startup.lua: please hold on...
oct. 15 15:57:30 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:30 [startup.lua:169] [lists_utils.lua:784] Refreshing category lists...
oct. 15 15:57:32 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:32 [startup.lua:169] [lists_utils.lua:717] Category Lists (23535 hosts, 76170
oct. 15 15:57:32 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:32 [startup.lua:288] Completed startup.lua
oct. 15 15:57:32 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:32 [PeriodicActivities.cpp:168] Each periodic activity script will use 4 threa
oct. 15 15:57:32 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:32 [NetworkInterface.cpp:3174] Started packet polling on interface eno2 [id: 3
oct. 15 15:57:32 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:32 [NetworkInterface.cpp:3174] Started packet polling on interface enp8s0f0 [i
oct. 15 15:57:32 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:32 [NetworkInterface.cpp:3174] Started packet polling on interface enp8s0f1 [i
oct. 15 15:57:33 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:33 [Ntop.cpp:2598] Registered interface OPEN_TOURS_EXIM(85) [id: 21]
oct. 15 15:57:33 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:33 [Ntop.cpp:2598] Registered interface COG_VIRTUAL_DMZ_INT(32) [id: 20]
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:3023] Started host user script hooks loop on interfac
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:2992] Started flow user script hooks loop on interfac
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:3174] Started packet polling on interface OPEN_TOURS_
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:3023] Started host user script hooks loop on interfac
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:3174] Started packet polling on interface COG_VIRTUAL
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:2992] Started flow user script hooks loop on interfac
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [Ntop.cpp:2598] Registered interface OPEN_TOURS_GUEST(127) [id: 23]
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [Ntop.cpp:2598] Registered interface OPEN_MCO_PPM(167) [id: 22]
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:2992] Started flow user script hooks loop on interfac
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:3174] Started packet polling on interface OPEN_MCO_PP
oct. 15 15:57:34 MCONSPP01 ntopng[48330]: 15/Oct/2021 15:57:34 [NetworkInterface.cpp:3023] Started host user script hooks loop on interfac
oct. 15 15:57:34 MCONSPP01 systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
oct. 15 15:57:34 MCONSPP01 systemd[1]: ntopng.service: Failed with result 'signal'.
oct. 15 15:57:39 MCONSPP01 systemd[1]: ntopng.service: Service RestartSec=5s expired, scheduling restart.
oct. 15 15:57:39 MCONSPP01 systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 109.
oct. 15 15:57:39 MCONSPP01 systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
oct. 15 15:57:39 MCONSPP01 systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
oct. 15 15:57:39 MCONSPP01 systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
oct. 15 15:57:40 MCONSPP01 ntopng[48502]: 15/Oct/2021 15:57:40 [Ntop.cpp:3286] Added Local Network 127.0.0.0/8
oct. 15 15:57:40 MCONSPP01 ntopng[48502]: 15/Oct/2021 15:57:40 [Ntop.cpp:3286] Added Local Network fe80::/10
oct. 15 15:57:40 MCONSPP01 ntopng[48502]: 15/Oct/2021 15:57:40 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
oct. 15 15:57:40 MCONSPP01 ntopng[48502]: 15/Oct/2021 15:57:40 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
oct. 15 15:57:40 MCONSPP01 ntopng[48502]: 15/Oct/2021 15:57:40 [NtopPro.cpp:330] [LICENSE] Reading license from /etc/ntopng.license
oct. 15 15:57:40 MCONSPP01 ntopng[48502]: 15/Oct/2021 15:57:40 [NtopPro.cpp:501] [LICENSE] /etc/ntopng.license: found valid Enterprise M l
```

I can't give you the developing tools's result because I've reconnected the link to the server's interface and the interface crash.
I've no time on each refresh to give you those information. I go to the DC to disconnect the link and will give you the dev tools information.

**Comment by MatteoBiscosi** [comment]
@thomasbruchet try to update to the latest version of ntopng, because we fixed a crash in ntopng and could be the same problem.
Just to get it better, do you add a new sub-interface from the menu below and it crashes? instantly crashes or it crashes just few minutes later?
![Screenshot from 2021-10-15 16-04-46](https://user-images.githubusercontent.com/49585191/137500360-e6414fbf-bfd4-469e-9d62-0c850dd4636c.png)

**Comment by thomasbruchet** [comment]
It didn't crash when I had them from the menu. 
That start to crash when I restart the service to applicate the change. 
The only way to have the interface without crash now is to disconnect the RJ45 link or when is it possible to have a few sec on the interface to put it in "pause" mode.

**Comment by MatteoBiscosi** [comment]
could you please send me your ntopng configuration? please drop an email at `biscosi at ntop.org`, unfortunately I cannot reproduce the behavior so I'll send you a debug build by email. Please follow these instructions to use the debug build https://github.com/ntop/ntopng/blob/dev/doc/README.crash.md

**Comment by thomasbruchet** [comment]
Here is the log of developer tools

![image](https://user-images.githubusercontent.com/86605223/137503488-70021101-2c13-44a8-a89e-7cba2cdc416c.png)

I will send the information by mail as requested

**Comment by thomasbruchet** [comment]
Edit; I will not have the time to do it today and I'm on on the office the next week. 
Can you put the "Issue" in pending until monday 25, I will not be able to send you the informations before this date.
Thank you.

**Comment by thomasbruchet** [comment]
Hello
The file has just been sent by email. 

For information:
WHen I try to delete a subinterface with () in the name I've this log:
25/Oct/2021 10:10:25 [LuaEngine.cpp:1219] WARNING Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/delete_sub_interface.lua][...opng/scripts/lua/pro/enterprise/delete_sub_interface.lua:22: Missing interface index]

**Comment by simonemainardi** [comment]
@MatteoBiscosi please check this

**Comment by simonemainardi** [comment]
Crash seems to be due to the nBPF tree match. Actually, it's the custom callback that contains an invalid address:

![image](https://user-images.githubusercontent.com/3397663/139818902-87c8bb21-c90b-4c32-9529-f84b034a292c.png)

**Comment by cardigliano** [comment]
It is likely this has been fixed in https://github.com/ntop/PF_RING/commit/b72ea12f66ab1962039687d211d791b002c76240

**Comment by thomasbruchet** [comment]
Hello;

After the debug session with simonemainardi this morning and an update of ntopng, the application start without any problem. 
Thank you for your support.

**Comment by simonemainardi** [comment]
Thanks for reporting this.

**Comment by thomasbruchet** [comment]
Hello;

Yesterday's debugging solved the multi-crash problem but I still have a problem with non-deletable interfaces.
![image](https://user-images.githubusercontent.com/86605223/140040290-77bed586-38be-477f-a364-4390a66279b4.png)
When I click on [Delete], nothing append.

**Comment by thomasbruchet** [comment]
nov. 03 10:56:52 MCONSPP01 ntopng[31420]: 03/Nov/2021 10:56:52 [LuaEngine.cpp:1253] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/delete_sub_interface.lua][...opng/scripts/lua/pro/enterprise/delete_sub_interface.lua:22: Missing interface index]
