### ISSUE TITLE
Possible memory leak on dev (Debian 10)

### ISSUE THREAD

**Issue by mikulov** [ntop/ntopng#6295]
Here is the screenshot of the memory usage stats for last two weeks. Major upgrade was done a week ago. When it's comes close to memory limits, ntop begin to lag and got restarted. Please advice how to stabilize it.

![image](https://user-images.githubusercontent.com/26163961/153124621-0629b724-7710-43bf-b2f6-db1aba5a06e1.png)

**Comment by MatteoBiscosi** [comment]
Hi @mikulov please share the output of your ntopng --version  (including OS, platform ecc.) we'll build a debugging version of ntopng and send it to you

**Comment by mikulov** [comment]
> Hi @mikulov please share the output of your ntopng --version (including OS, platform ecc.) we'll build a debugging version of ntopng and send it to you

Thank you for your feedback

ntopng Enterprise L v.5.3.220209 rev.16798 (Ubuntu 18.04.6 LTS) 
Debian buster/sid [x86_64][Ubuntu 18.04.6 LTS] - 64 bit

**Comment by cardigliano** [comment]
@mikulov I will provide you a binary with leak detection enabled.

**Comment by cardigliano** [comment]
I sent you a link with the binary

**Comment by yavuzaydin** [comment]
We experience the same on Debian 11, here is the relevant output of ntopng --version:
Version:        5.2.220326 [Enterprise/Professional build]
GIT rev:        5.2-stable:105b301435a52a78e43c3b19c8d85a44dc103298:20220326
Pro rev:        r4750
Built on:       Debian GNU/Linux 11 (bullseye)
Platform:       x86_64
Edition:        Enterprise L (Bundle)

**Comment by cardigliano** [comment]
@yavuzaydin are you able to provide access to your system for debugging perhaps?

**Comment by yavuzaydin** [comment]
Yes this is possible if you send me an e-mail with your public key.

**Comment by cardigliano** [comment]
Please send a direct email to cardigliano at ntop.org

**Comment by cardigliano** [comment]
It seems that migrating from nIndex to ClickHouse made memory utilization stable for the @yavuzaydin installation, still monitoring that.

**Comment by N3S1** [comment]
We're experiencing the same issue on a redhat system:
Version:        5.2.220326 [Enterprise/Professional build]
GIT rev:        5.2-stable:105b301435a52a78e43c3b19c8d85a44dc103298:20220326
Pro rev:        r4750
Built on:       Rocky Linux release 8.5 (Green Obsidian)
Platform:       x86_64
Edition:        Enterprise L (Bundle)

Kernel:        4.18.0-348.20.1.el8_5.x86_64

**Migration from nIndex to Clickhouse-server didn't solve the issue for our installation!**


@cardigliano We've already send you an email!

**Comment by mikulov** [comment]
After last update, working stable for 10+ days. Thank you very much @cardigliano 

<img width="1563" alt="Screenshot 2022-04-07 at 19 28 01" src="https://user-images.githubusercontent.com/26163961/162222791-4e3360ed-e7ff-46e9-bfb6-9a1649bf8825.png">

**Comment by N3S1** [comment]
Dear @mikulov,
good to hear that you are not affected by the problem any more!

Could you tell us which version you're using, or give us the output of your "ntopng --version" command?

**Comment by mikulov** [comment]
Version:        5.3.220323 [Enterprise/Professional build]
GIT rev:        dev:70b630600521d7708d1ed212b62b31546b5487b1:20220323
Pro rev:        r4860
Built on:       Ubuntu 18.04.6 LTS
Platform:       x86_64
Edition:        Enterprise L (Bundle)

**Comment by cardigliano** [comment]
Is there anyone still affected by this? It seems this has been fixed, at least looking at the systems I was monitoring.

**Comment by thomasbruchet** [comment]
Hello,

I still lhave the issue since https://github.com/ntop/ntopng/issues/6320
This is my graph right now on: [ntopng Enterprise M v.5.3.220401 (Debian GNU/Linux 10 (buster))]
![image](https://user-images.githubusercontent.com/86605223/163340656-2ac40bce-377f-48b5-be86-86a0cd4319a5.png)
![image](https://user-images.githubusercontent.com/86605223/163341742-764dfe05-a7a9-476e-98e7-283ae456ef82.png)

I've migrated to ClickHouse on my last update April 01 but didn't seems solve the issue. 

I've not the System graph to share (no icon)
Here is the data of ClickHouse, is it normal that the Flow table so large ?
![image](https://user-images.githubusercontent.com/86605223/163341465-a665a640-fdc9-4700-9547-97aa21713224.png)

Here is my mem usage on the system:
![image](https://user-images.githubusercontent.com/86605223/163341636-d235ab35-b1ec-49f5-b659-48168589eccc.png)

**Comment by N3S1** [comment]
@thomasbruchet Dunno if this helps, but there seems to be a new version in the Debian (Bullseye) stable Repo "[ntopng_5.2.220408-17421_amd64.deb](https://packages.ntop.org/apt-stable/bullseye/x64/ntopng_5.2.220408-17421_amd64.deb)".



What i can tell you so far, is that Clickhouse is not the solution for the memory leak problem!


(We in particular, have rollbacked to a previous version, but only because we have daily backups from our VMs for a large period.
In due time (roundabout 2 weeks) we could tell you if the actual version is fixing the leak issue, but we don't use a debian based system so it's probably not transferable.)

**Comment by N3S1** [comment]
We've tested againg with the following version:
Version:        5.2.220420 [Enterprise/Professional build]
GIT rev:        5.2-stable:08227827a52b7e80612c42182194b780d4db93f4:20220420
Pro rev:        r4752
Built on:       Rocky Linux release 8.5 (Green Obsidian)


**But the issue STILL EXISTS, so we're again doing a rollback to a previous version...**

**Comment by cardigliano** [comment]
@mikulov could you confirm that this has been addressed and working in the latest version? Thank you.
