### ISSUE TITLE
Fail build version 5.2

### ISSUE THREAD

**Issue by Pro-pra** [ntop/ntopng#6312]
I build with gcc and build fail with messages:

> 
> DEBUG: src/Host.cpp: In member function 'bool Host::isHostAlertDisabled(HostAlertType)':
> DEBUG: src/Host.cpp:1726:10: error: 'alert_exclusions' was not declared in this scope
> DEBUG:  1726 |   return(alert_exclusions.isSetHostExclusionBit(alert_type.id));
> DEBUG:       |          ^~~~~~~~~~~~~~~~
> DEBUG: src/Host.cpp: In member function 'bool Host::isFlowAlertDisabled(FlowAlertType)':
> DEBUG: src/Host.cpp:1734:10: error: 'alert_exclusions' was not declared in this scope
> DEBUG:  1734 |   return(alert_exclusions.isSetFlowExclusionBit(alert_type.id));
> DEBUG:       |          ^~~~~~~~~~~~~~~~
> DEBUG: make: *** [Makefile:130: src/Host.o] Error 1
>

**Comment by Pro-pra** [comment]
may be this string for Pro version?

**Comment by MatteoBiscosi** [comment]
Hi @Pro-pra, if you update the issue is already resolved

**Comment by MatteoBiscosi** [comment]
Verified as Fixed

**Comment by Pro-pra** [comment]
thank you

**Comment by rnalrd** [comment]
Sorry for the dumb question: is there a fix not yet released? I don't see any commit relevant to this problem and I still have the same problem.
