### ISSUE TITLE
Can't list protocols on protocols tab for host.

### ISSUE THREAD

**Issue by matt876** [ntop/ntopng#638]
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close Script "/usr/share/ntopng/scripts/lua/host_details_ndpi.lua" returned an error:
Works in ntopng-2.5

**Comment by lucaderi** [comment]
In 2.5 works, whereas in what version does not work?

**Comment by matt876** [comment]
2.4 is what I am having problems with. 

Matt FridenstineNorth Coast Wireless Communications440-506-1798
Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by matt876** [comment]
I updated to  v.2.4.160704 today and I still have the same problem viewing the protocols list.

So far 2.4 seems stable. 2.5 would not stay running for more than 30 minutes under load. We are running at peak 1Gbps through it.

**Comment by simonemainardi** [comment]
we are aware of an nDPI bug https://github.com/ntop/nDPI/issues/225 that is causing crashes in version 2.5. @kYroL01 is looking at it.

**Comment by lucaderi** [comment]
@matt876 The nDPI issue has been solved. Please confirm ntopng is working now.

**Comment by matt876** [comment]
2.5.160706 is not crashing, however it stopped receiving or processing data about 2 hours after running. Investigating further.

**Comment by simonemainardi** [comment]
look at the interface overview page _dropped packets_ and see if there is something strange going on. Can you post the the startup string used?

**Comment by matt876** [comment]
I am using all yum and RPM based installs. My config file contains local networks and two interfaces.

I just updated drivers, cleared old data off the disks and fix a couple issues I found in the log files. Running for now so if it fails again I will do more digging. Thanks

**Comment by matt876** [comment]
It is still failing. Just stops processing data. Nothing in the logs.

No Ethernet errors or drops.

ntopng.conf

-G=/var/tmp/ntopng.pid

#-F="mysql;localhost;ntopng;flows;ntopng;d0ntf0rg3t"

--data-dir /home/ntopng/data

--interface=eth1

--interface=eth2

--local-networks="208.93.184.0/21,199.87.176.0/21,172.16.0.0/12,10.0.0.0/8,192.1

68.0.0/16"

[root@nx-ic-ntop01 ~]# more /etc/init.d/ntopng

#! /bin/bash

#

# (C) 2003-16 - ntop.org

#

# chkconfig: 2345 80 30

#

### BEGIN INIT INFO

# Provides:          ntopng

# Required-Start:    $local_fs $remote_fs $network $syslog $pf_ring

# Required-Stop:     $local_fs $remote_fs $network $syslog

# Default-Start:     2 3 4 5

# Default-Stop:      0 1 6

# Short-Description: Start/stop ntopng web

### END INIT INFO

DISTRO="unknown"

if [ -f /lib/lsb/init-functions ]; then

   DISTRO="debian"

   . /lib/lsb/init-functions

fi

if [ -f /etc/init.d/functions ]; then

   DISTRO="centos"

   . /etc/init.d/functions

fi

ERROR=0

NTOPNG_BINARY=/usr/bin/ntopng

#

# This to avoid issues in case there are local files

# (Example when ntopng has been cloned from git)

#

cd /

error_handler() {

```
EXIT_ON_END=$0



if [ -n "${MSG}" ]; then

    if [ ${ERROR} -gt 0 ]; then

        if [ ${DISTRO} == "debian" ]; then

            log_failure_msg "${MSG}"

            log_end_msg $ERROR

        elif [ ${DISTRO} == "centos" ]; then

            echo -n ${MSG}

            echo_failure; echo

        fi

    else

        [ ${DISTRO} == "debian" ] && log_end_msg $ERROR

        [ ${DISTRO} == "centos" ] && echo_success && echo

    fi

fi



if [ "$EXIT_ON_END" == "quit" ]; then

    exit 99

fi
```

}

get_ntopng_pid() {

```
PID=0



if [ -f "/etc/ntopng/ntopng.conf" ]; then

    PID_FILE=$(cat /etc/ntopng/ntopng.conf | grep -v '^#' | grep -E '\-G=|--pid'|cut -d '=' -f 2)

else

    PID_FILE="/var/run/ntopng.pid"

fi



if [ -z $PID_FILE ]; then

    return 0

fi



if [ -f $PID_FILE ]; then

    PID=$(cat $PID_FILE)

    if [ -z ${PID} ]; then

        /bin/rm $PID_FILE

    else

        if [ ${PID} -gt 0 ]; then

            IS_EXISTING=$(ps auxw | grep -w $PID | grep -v grep | wc -l)

            if [ ${IS_EXISTING} -gt 0 ]; then

               return $PID

            else

                /bin/rm $PID_FILE

            fi

        fi

    fi

fi



return 0
```

}

start_ntopng() {

   RETVAL=0

   FORCE=$1

```
if [ ! -d "/etc/ntopng" ]; then

    #echo "Configuration directory /etc/ntopng does not exist: quitting..."

    #echo "This package is designed to be used from within the nBox package that"

    #echo "configures ntopng using a web GUI. Please install the nBox package"

    #echo "from http://packages.ntop.org"

    #MSG="Default directory is missing. Quitting"

    #ERROR=1

    #RETVAL=1

    echo "Creating directory /etc/ntopng"

    mkdir /etc/ntopng

fi



if [ ! -f "/etc/ntopng/ntopng.conf" ]; then

    echo "Generating configuration file /etc/ntopng/ntopng.conf"

    echo "-G=/var/run/ntopng.pid" > /etc/ntopng/ntopng.conf

    if [ -d /storage ]; then

        if [ ! -d /storage/ntopng ]; then

            mkdir /storage/ntopng

            chmod gou+rxw /storage/ntopng

        fi



        echo "-d=/storage/ntopng" >> /etc/ntopng/ntopng.conf

    fi

    CHECK_P4P1=`grep p4p1 /proc/net/dev|wc -l`

    if [ $CHECK_P4P1 -eq 1 ]; then

        echo "-i=p4p1" >> /etc/ntopng/ntopng.conf

    fi

    touch /etc/ntopng/ntopng.start

fi



if [ -f /etc/ntopng/ntopng.start ] || [ $FORCE -eq 1 ]; then

    [ ${DISTRO} == "debian" ] && log_daemon_msg "Starting ntopng"

    [ ${DISTRO} == "centos" ] && echo -n "Starting ntopng: "



    get_ntopng_pid

    if [ ${PID} -gt 0 ]; then

        MSG="ntopng already running. Quitting"

        ERROR=1

        RETVAL=1

        error_handler "quit"

        exit 99

    fi

    if [ ! -d /var/log/ntopng/ ]; then

       mkdir -p /var/log/ntopng/

       touch  /var/log/ntopng/ntopng.log

       chmod 777  /var/log/ntopng/ntopng.log

    fi

    $NTOPNG_BINARY /etc/ntopng/ntopng.conf >> /var/log/ntopng/ntopng.log &



    for i in {1..5}

    do

        get_ntopng_pid

        if [ ${PID} -gt 0 ]; then

            MSG="Started ntopng with PID $PID"

            ERROR=0

            break

        else

            MSG="Unable to start ntopng"

            ERROR=1

            sleep 1

        fi

    done



    if [ $ERROR -gt 0 ]; then

        error_handler "quit"

    else

        [ ${DISTRO} == "debian" ] && log_end_msg $ERROR

        [ ${DISTRO} == "centos" ] && echo_success && echo

    fi

else

    MSG="Missing /etc/ntopng/ntopng.start. Quitting"

    ERROR=1

    RETVAL=1

    error_handler "quit"

fi
```

}

stop_ntopng() {

```
RETVAL=0

[ ${DISTRO} == "debian" ] && log_daemon_msg "Stopping ntopng"

[ ${DISTRO} == "centos" ] && echo -n "Stopping ntopng: "



get_ntopng_pid



if [ -z ${PID} ]; then

    return 0

fi



if [ ${PID} -eq 0 ]; then

    if [ ! -f "/etc/ntopng/ntopng.conf" ]; then

        MSG="Missing /etc/ntopng/ntopng.conf"

        ERROR=1

        RETVAL=1

        error_handler

    fi



    return 0

fi



# Do we really need this check?

#if [ ! -d "/etc/ntopng" ]; then

#    MSG="Default directory is missing. Quitting"

#    error_handler "quit"

#   [ ${DISTRO} == "debian" ] && log_end_msg $ERROR

#   [ ${DISTRO} == "centos" ] && echo_success && echo

#   return 0

#fi



MSG=

for i in {1..5}

do

    get_ntopng_pid

    if [ ${PID} -gt 0 ]; then

        kill -15 $PID &> /dev/null

        MSG="Sent kill to ntop PID $PID"

        sleep 1

    else

        MSG="Stopped ntopng PID $PID"

        break

    fi

done

ERROR=0



error_handler
```

}

status_ntopng() {

```
if [ ! -d "/etc/ntopng" ]; then

    MSG="Default directory is missing. Quitting"

    ERROR=1

    RETVAL=1

    error_handler "quit"

fi



if [ ! -f "/etc/ntopng/ntopng.conf" ]; then

    MSG="Configuration file is missing. Quitting"

    ERROR=1

    RETVAL=1

    error_handler "quit"

fi



get_ntopng_pid

if [ ${PID} -gt 0 ]; then

    echo "ntopng running as ${PID}"

else

    echo "ntopng is not running"

    exit 1

fi



return 0
```

}

########

logger "ntopng $1"

case "$1" in

  start)

```
    start_ntopng 0;

    ;;
```

  force-start)

```
    if [ ! -f /etc/ntopng/ntopng.conf ]; then

        echo "ERROR: No configuration file found"

        exit 1

    fi

    start_ntopng 1;

    ;;
```

  stop)

```
    stop_ntopng;

    ;;
```

  status)

```
    status_ntopng;

    ;;
```

  restart)

```
    stop_ntopng;

    start_ntopng 0;

    ;;
```

  *)

```
    echo "Usage: /etc/init.d/ntopng {start|force-start|stop|restart|status}]"

    exit 1
```

esac

exit 0

**Comment by lucaderi** [comment]
@matt876 Please generate a core dump and send me both the ntopng binary and the core. Thanks

**Comment by matt876** [comment]
Working on the dump. I noticed after letting this sit for some time there are now dropped packets in the interface status page.

**Comment by gmourani** [comment]
Hello,

I got the same issue with version 2.4 on CentOS 6.7.
[Lua.cpp:5134] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details_ndpi.lua][table index is nil]

Gerhard,

**Comment by gmourani** [comment]
This happen for me when running in proxy mode --http-prefix /ntopng

**Comment by simonemainardi** [comment]
I went through the error reported

The error is caused by 
`[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized`

The error above, in turn, determines the insertion of a `nil` value as key in the lua table obtained with `interface.getnDPIProtocols()` and, consequently, the following error is raised
`
[Lua.cpp:5134] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details_ndpi.lua][table index is nil]`

protocol 226 is Git so, as this protocol is one of the latest additions, I guess the nDPI version used to build ntopng 2.4 should be updated. @lucaderi can you please check. Thank you.

**Comment by gmourani** [comment]
Hello Luca,

You are right, using the latest nDPI and recompiling 2.4 with it solved the problem.

Gerhard,

**Comment by simonemainardi** [comment]
thanks for giving feedback. So compiling from sources solves the issue. However, we should be able to fix this also in packaged binaries.

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/nDPI/commit/72e3930e088c9e6df51f7f314935167c63b8d0ad

**Comment by matt876** [comment]
I installed 2.5.160712 yesterday and it has been perfectly stable for 24 hours.

**Comment by simonemainardi** [comment]
thanks for reporting
