### ISSUE TITLE
Dashboard AJAX requests running very slowly

### ISSUE THREAD

**Issue by basicmonkey** [ntop/ntopng#6483]
**Environment**:
Ubuntu 20.04.4 amd64
ntopng Enterprise M v.5.3.220330
Clickhouse flow recording
3x Remote nProbe instances

**What happened**:
Login page to dashboard opens instantly. Dashboard refresh runs very slowly. Using Chrome inspector, I can see AJAX requests to talkers take 15-20 seconds.

Seems like the same issue at: https://github.com/ntop/ntopng/issues/6373

**What did you expect to happen?**
Dashboard to refresh every 10 seconds and only take a second or so to do it.

**How did you reproduce it?**
Log in and open dashboard.

**Debug Information**:
This is the same with Clickhouse enabled or removed from configuration.
top shows no issue with CPU or memory use.

iowait: 0.4% / active: 23.87% / idle: 75.73%

<img width="1069" alt="Screenshot 2022-03-30 at 15 20 50" src="https://user-images.githubusercontent.com/392058/160857292-5a572ae3-d86d-4fe5-bd07-cd24fe4e61c7.png">

**Comment by MatteoBiscosi** [comment]
Hi @basicmonkey in which page do you see this problem? Try to update to the latest ntopng version that we pushed a couple of fixes regarding this one. Are you using a VPN? because we saw that using a VPN sometimes slow a lot the ajax requests

**Comment by basicmonkey** [comment]
Hi @MatteoBiscosi this is on all pages, even non data specific ones such as system_stats. I've upgraded to: [ntopng Enterprise M v.5.3.220412] and no change. All AJAX requests are around 10 seconds on system_stats.

dashboard.lua takes 20seconds to load and data.lua AJAX requests take about 10 seconds when in dashboard. I've disabled the probes to see if no data helps, still the same. talkers.lua requests take 50-60ms.

**Comment by basicmonkey** [comment]
Not over VPN either. Over ethernet, full size MTU etc.

**Comment by MatteoBiscosi** [comment]
Hi @basicmonkey we were able to debug this problem and to understand the source of the problem.
In all our cases, the problem arose with a firewall blocking some specific traffic ntopng does (for instance the blacklisted lists, google, ecc), so please add this exceptions to your firewall https://www.ntop.org/support/faq/to-what-ip-domain-names-ntopng-connects-to/ and everything should work correctly.
We tested with 3 different customers and everyone fixed the problem with it.
Other then excluding those url you could try adding the `--offline`, in this way ntopng won't try to do internet traffic.
The problem is fixed in the 5.3 version (dev version)

**Comment by basicmonkey** [comment]
Hi @MatteoBiscosi Thanks for letting me know. My firewall doesn't block any outgoing requests from the ntop VM. It can talk to anything. Only Russian and Belarusian IPs are blocked at the moment!

I've tried --offline in v.5.3.220517 and makes no difference. Still 15second AJAX requests.

**Comment by basicmonkey** [comment]
Can you please reopen this?

**Comment by MatteoBiscosi** [comment]
Hi @basicmonkey yeah sure, you have to reopen the ticket if it's not working.

**Comment by MatteoBiscosi** [comment]
Could you please help me debugging this problem?
To understand what's taking this time you have to help me with the curl.
Run these commands and let me know which is taking the most time and which is instead fast.
`curl http://localhost:3000/dist/third-party.js`
`curl http://localhost:3000/dist/third-party.css`
`curl http://localhost:3000/lua/admin/edit_configset.lua?subdir=all`
Instead of `localhost:3000` you have to use `ntop.basic` i think (the url to connect to ntopng)

**Comment by basicmonkey** [comment]
Sorry for the delay. First two requests are instant, no delay whatsoever. All statically served elements are fine.

The third command returns an empty line. Maybe an auth thing as curl not logged in?

**Comment by MatteoBiscosi** [comment]
yes sorry this is an example:
`curl -s --verbose --cookie "user=admin; password=admin" "http://localhost:3000/lua/admin/edit_configset.lua?subdir=all"`

**Comment by basicmonkey** [comment]
Thanks. That took about 10 seconds.

**Comment by MatteoBiscosi** [comment]
Hi @basicmonkey yeah, it's the issue I told you about above, probably some request to google or some request to the internet blocks .lua script, could you please check the requests done during the curl? maybe we can understand which request is blocked

**Comment by MatteoBiscosi** [comment]
Closing for inactivity, please reopen if needed; however consider that the problem is some sort of firewall blocking ntopng requests to the internet.

**Comment by basicmonkey** [comment]
Hi @MatteoBiscosi

Theres absolutely nothing stopping this VM talking to the internet:

```
root@nms:/home/nms# dig google.com

; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11283
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		172	IN	A	216.58.212.238

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Jul 04 11:10:36 UTC 2022
;; MSG SIZE  rcvd: 55

root@nms:/home/nms# ping google.com
PING google.com (216.58.212.238) 56(84) bytes of data.
64 bytes from lhr25s28-in-f14.1e100.net (216.58.212.238): icmp_seq=1 ttl=118 time=9.21 ms
64 bytes from lhr25s28-in-f14.1e100.net (216.58.212.238): icmp_seq=2 ttl=118 time=9.73 ms
64 bytes from lhr25s28-in-f14.1e100.net (216.58.212.238): icmp_seq=3 ttl=118 time=9.61 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 9.214/9.520/9.734/0.222 ms
root@nms:/home/nms# nc google.com 80
GET
HTTP/1.0 200 OK
Date: Mon, 04 Jul 2022 11:11:02 GMT
Expires: -1
Cache-Control: private, max-age=0
Content-Type: text/html; charset=ISO-8859-1
```

My maintenance has just expired so I can't grab any more updates. I'm not keen to keep spending lots of money on ntop with this issue preventing me from using it.

**Comment by basicmonkey** [comment]
HTTPS requests working fine too:

```
root@nms:/home/nms# curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

**Comment by MatteoBiscosi** [comment]
The issue is not fixed

**Comment by MatteoBiscosi** [comment]
Verified as fixed

**Comment by TalalMash** [comment]
Running latest ntopng on an OpenWRT ARM router, `--offline` still shows significant performance improvement.
