### ISSUE TITLE
Timeseries'es of Active Monitoring are showing wrong values

### ISSUE THREAD

**Issue by lumarel** [ntop/ntopng#7347]
**Environment**:
* OS name: Rocky Linux
* OS version: 8.7
* Architecture: x86_64
* ntopng version/revision: 5.7.230319 [Enterprise/Professional build]

**What happened**:

I am using the Active Monitoring for constant speedtesting, but also ICMP tests for the main routers:
![Screenshot from 2023-03-25 21-24-35](https://user-images.githubusercontent.com/42647570/227739907-8269102c-03d9-43ec-8484-f77d89bb83a2.png)
If I look at the timeseries of both the Speedtest as well as the ICMP tests, it shows completely different values:
![image](https://user-images.githubusercontent.com/42647570/227740070-01a2ba87-c13c-41c1-9bd5-1413b8100d07.png)
![Screenshot from 2023-03-25 21-30-20](https://user-images.githubusercontent.com/42647570/227740158-6a99a852-fb68-4c05-876e-66232fcdd564.png)

**How did you reproduce it?**

- Create a Speedtest/ICMP Active Monitoring record
- Wait for the history to build up

**Debug Information**:

There was not really any apparent log entries, in the system journal, the log file and also not in the browser console log.
If I can provide any further information, I will gladly do that.

**Comment by MatteoBiscosi** [comment]
Hi @lumarel what do you mean by different values? in the first screenshot, you have the download speed and in the second one the min/max RTT (two different measurements).

**Comment by lumarel** [comment]
@MatteoBiscosi There are 3 screenshots,
the first shows the overview, there you can see that my connection had 184.64 Mbps and the ICMP checks 0.17 and 20.12 ms. (and these values are pretty constant)
The 2nd and 3rd image show the timeseries behind these measurements, but as you can see the values are somehow very different from the current one, 1.48 Kbps as the peak for the speedtest. (there are also Min/Max RTT, which looks to be accurate in the timeseries, and Upload speed, which shows average value of 655.44 Mbps, which is like.. 10x of my maximum upload, available)
And both timeserieses for the ICMP test only show an empty graph for the RTT time (there are no other values available)

**Comment by MatteoBiscosi** [comment]
Hi @lumarel you are right, i didn't see the difference, I'm going to investigate the issue and update you

**Comment by MatteoBiscosi** [comment]
Hi @lumarel I pushed a fix, unfortunately, the data itself where wrongly saved, so the previous speed test data are incorrect.
In a couple of hours update and let me know if the newly added data are correct.

**Comment by lumarel** [comment]
That's no dealbreaker for me, I haven't started to use it as a major source for that data.
Still waiting for the update, so will tell you tomorrow how it went 👍🏻

**Comment by lumarel** [comment]
@MatteoBiscosi Okay great! After the update the Download-Timeseries show the correct new values for everything after the update, thank you!
Interestingly Min/Max RTT and Upload Timeserieses are gone now (and ICMP RTT Timeserieses are still not working)

**Comment by lumarel** [comment]
@MatteoBiscosi Hm as said in my previous comment, the download timeseries is fixed now, but upload and min/max RTT are gone now, and the ICMP RTT timeseries is still not working :)
