### ISSUE TITLE
Adding SNMP device succeeded, but polling failed

### ISSUE THREAD

**Issue by dudumao520** [ntop/ntopng#7353]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 22.04.2]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.6.230327]

**What happened**:

Adding SNMP device was successful, but polling failed,Only the SNMP devices of the host where ntopng resides can be added and polled normally

**How did you reproduce it?**
I have updated the version twice, but the problem still exists

**Debug Information**:

root@test-server:~# journalctl -xe -u ntopng
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:306: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]:  string SNMP response: 2
Mar 29 15:40:05 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:05 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_cdp.lua:16: in function 'snmp_dev.check_cdp_mib_availability'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:307: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]:  string SNMP response: 4
Mar 29 15:40:05 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:05 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_lldp.lua:16: in function 'snmp_dev.check_lldp_mib_availability'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:306: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]: 29/Mar/2023 15:40:05 [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils>
Mar 29 15:40:05 test-server ntopng[1045]: [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:162: bad argumen>
Mar 29 15:40:05 test-server ntopng[1045]:  string SNMP response: 4
Mar 29 15:40:05 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:05 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_cdp.lua:16: in function 'snmp_dev.check_cdp_mib_availability'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:307: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]: 29/Mar/2023 15:40:05 [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils>
Mar 29 15:40:08 test-server ntopng[1045]: [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:162: bad argumen>
Mar 29 15:40:08 test-server ntopng[1045]:  string SNMP response: 0
Mar 29 15:40:08 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:08 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_lldp.lua:16: in function 'snmp_dev.check_lldp_mib_availability'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:306: in function 'snmp_dev.poll_device'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:08 test-server ntopng[1045]:  string SNMP response: 0
Mar 29 15:40:08 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:08 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_cdp.lua:16: in function 'snmp_dev.check_cdp_mib_availability'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:307: in function 'snmp_dev.poll_device'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:08 test-server ntopng[1045]: 29/Mar/2023 15:40:08 [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils>
root@test-server:~# journalctl -xe -u ntopng | less
root@test-server:~# journalctl -xe -u ntopng | less
root@test-server:~# journalctl -xe -u ntopng
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:306: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]:  string SNMP response: 2
Mar 29 15:40:05 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:05 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_cdp.lua:16: in function 'snmp_dev.check_cdp_mib_availability'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:307: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]:  string SNMP response: 4
Mar 29 15:40:05 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:05 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_lldp.lua:16: in function 'snmp_dev.check_lldp_mib_availability'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:306: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]: 29/Mar/2023 15:40:05 [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils>
Mar 29 15:40:05 test-server ntopng[1045]: [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:162: bad argumen>
Mar 29 15:40:05 test-server ntopng[1045]:  string SNMP response: 4
Mar 29 15:40:05 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:05 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_cdp.lua:16: in function 'snmp_dev.check_cdp_mib_availability'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:307: in function 'snmp_dev.poll_device'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:05 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:05 test-server ntopng[1045]: 29/Mar/2023 15:40:05 [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils>
Mar 29 15:40:08 test-server ntopng[1045]: [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:162: bad argumen>
Mar 29 15:40:08 test-server ntopng[1045]:  string SNMP response: 0
Mar 29 15:40:08 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:08 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_lldp.lua:16: in function 'snmp_dev.check_lldp_mib_availability'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:306: in function 'snmp_dev.poll_device'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:08 test-server ntopng[1045]:  string SNMP response: 0
Mar 29 15:40:08 test-server ntopng[1045]:  string stack traceback:
Mar 29 15:40:08 test-server ntopng[1045]:         .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils.lua:324: in function 'snmp_dev._snmpgetnextbulk'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev_cdp.lua:16: in function 'snmp_dev.check_cdp_mib_availability'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_dev.lua:307: in function 'snmp_dev.poll_device'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:83: in upvalue '_poll_devices'
Mar 29 15:40:08 test-server ntopng[1045]:         /usr/share/ntopng/pro/scripts/lua/modules/snmp_poll.lua:276: in function </usr/share/ntopng/pro/scripts/lua/modules/s>
Mar 29 15:40:08 test-server ntopng[1045]: 29/Mar/2023 15:40:08 [snmp_polling.lua:22] [snmp_poll.lua:305] ERROR: .../share/ntopng/pro/scripts/lua/modules/snmp_dev_utils>
lines 958-1000/1000 (END)

![123](https://user-images.githubusercontent.com/12032241/228463080-aa175a8f-812b-4113-922e-45d52a69ba7b.png)

**Comment by dudumao520** [comment]
[ntopng.log](https://github.com/ntop/ntopng/files/11097839/ntopng.log)

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520, I added a debug print in SNMP logs to understand what is happening and why the poll fails. We already tried to reproduce by all means your situation but everything seems working fine.
In a couple of hours a new build should be available, please update, then jump to the terminal of the system on which ntopng is installed and run this command

redis-cli SET "ntopng.debug.print_snmp_debug" 1

![image](https://user-images.githubusercontent.com/49585191/228502223-bd3e68bb-0f64-4902-b4e8-f67ea26d18fb.png)

In this way, new debug logs should appear in the ntopng logs to understand which poll is failing, like:
![image](https://user-images.githubusercontent.com/49585191/228501903-a0e9cfb0-abf6-46f9-b00b-d53cb83a3cf9.png)

After you have some logs with the polling (10/15 minutes are enough), run to remove the debug logs:

redis-cli DEL 'ntopng.debug.print_snmp_debug'

![image](https://user-images.githubusercontent.com/49585191/228502543-53192b25-8de9-4b91-8505-ce4eebb9bbbb.png)

Then send me the ntopng logs with those prints (if you prefer, you can share them directly by email at ' biscosi at ntop.org ' )

**Comment by dudumao520** [comment]
OS name: [e.g. Ubuntu]
OS version: [e.g. 22.04.2]
Architecture: [e.g. amd64]
ntopng version/revision: [e.g. 5.6.230329]


Hello, thank you for your help. I just returned from a business trip, and I upgraded the version again. I found that the ntopng service could not be started. Please help analyze the cause of the fault, thank you！
[ntopng-20230331.log](https://github.com/ntop/ntopng/files/11121144/ntopng-20230331.log)

The following error message is reported:
" /usr/bin/ntopng: error while loading shared libraries: libhiredis.so.0.14: cannot open shared object file: No such file or directory"

**Comment by dudumao520** [comment]
![123](https://user-images.githubusercontent.com/12032241/229105829-b83bc795-0035-4b5c-a1f3-34a42a10d821.png)
![1112233](https://user-images.githubusercontent.com/12032241/229105842-f461428f-41a7-4bc0-8ada-757da485e54f.png)

**Comment by dudumao520** [comment]
Hello, thank you for your help! I have just returned from a business trip and have conducted a test according to the method described by you. The following is the detailed log information
[ntop.0331.log](https://github.com/ntop/ntopng/files/11121458/ntop.0331.log)

**Comment by dudumao520** [comment]
![Uploading 11.png…]()

**Comment by dudumao520** [comment]
![11](https://user-images.githubusercontent.com/12032241/229112861-53f6f379-f09c-4fb6-8a3e-6619d442ca8d.png)

**Comment by dudumao520** [comment]
@lucaderi @MatteoBiscosi

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520 sorry but I didn't see the messages, I pushed a possible fix now, sorry for the "try and error" but we are totally unable to reproduce your issue due to the different devices we have and different oid we pull. Please let me know if with this fix the issue is fixed or not

**Comment by dudumao520** [comment]
Hello, after upgrading the version, I have added a new SNMP device. This time, the SNMP service running on the Windows 10 system can be polled normally, while the other two running on the Ubuntu 22.04.2 system still fail to poll:(
[ntop-20230405.log](https://github.com/ntop/ntopng/files/11157507/ntop-20230405.log)
![2](https://user-images.githubusercontent.com/12032241/230047717-0eb4dce0-df33-4e16-81ed-aaf87b9fd293.png)
![1](https://user-images.githubusercontent.com/12032241/230047722-32057e63-0760-42fa-bb47-039c47b0ceda.png)

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520 , please click on the 192.168.1.111 device and check if there are informations there, for example
![Screenshot 2023-04-05 120201](https://user-images.githubusercontent.com/49585191/230049155-bcadd588-b2f8-44e0-881f-0c13a17e0d12.png)
![Screenshot 2023-04-05 120209](https://user-images.githubusercontent.com/49585191/230049152-9409618f-b8c4-4dc5-8c9a-53e54336394b.png)
![Screenshot 2023-04-05 120224](https://user-images.githubusercontent.com/49585191/230049157-e32e3689-1d2e-4351-ad1e-e7d6d44d8605.png)
Because the ip is highlighted so it seems that some information are present and you don't have errors in your log.

**Comment by dudumao520** [comment]
![11](https://user-images.githubusercontent.com/12032241/230049764-0745088a-0e3e-4e73-bc0f-26705bf39e5e.png)
@MatteoBiscosi

**Comment by dudumao520** [comment]
Hello, after adding SNMP devices, there will be no longer a polling failure prompt, but other devices cannot be found in the interface function bar. Only IP120 (SNMP-ntopng-server) and IP100 (SNMP-swtich) can be found.I have plenty of time now. What tests do I need to do?

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520 let me check again the log. While checking the logs i found that all the blacklists are not unreachable. If for some reasons requests to the outside are blocked (for example in an enclosed system) I highly suggest on adding the ' --offline ' option to ntopng configuration file, in order to reduce the startup (and other operation) time.

**Comment by MatteoBiscosi** [comment]
can you please run the snmpget of this oid: 1.3.6.1.4.1.9.9.23.1.2.1 for the 192.168.1.111 host? Again, if you have sensible info drop me an email at ' biscosi at ntop.org '

**Comment by dudumao520** [comment]
root@print-server:~# snmpwalk -v 2c -c alex 192.168.1.111 1.3.6.1.4.1.9.9.23.1.2.1
SNMPv2-SMI::enterprises.9.9.23.1.2.1 = No Such Object available on this agent at this OID

**Comment by MatteoBiscosi** [comment]
Which information does the snmpwalk of the whole system return?
Because for example this oid 1.3.6.1.4.1.9.9.23.1.2.1 was the one failing before and the reason for failure is because it does not exist.
Can you please directly run the ' snmpwalk -v 2c -c alex 192.168.1.111 '?

**Comment by dudumao520** [comment]
[snmp.log](https://github.com/ntop/ntopng/files/11157870/snmp.log)
@MatteoBiscosi

**Comment by dudumao520** [comment]
@MatteoBiscosi Hi.is there anything I need to test?

**Comment by MatteoBiscosi** [comment]
just one last thing, could you enable snmp time series and let me know if the time-series are there tomorrow?
![image](https://user-images.githubusercontent.com/49585191/230115489-ca243a98-d49f-4ede-acea-be2587f48f51.png)

**Comment by dudumao520** [comment]
Hi. I have enabled the SNMP timing database, and the effect is as follows:
![112](https://user-images.githubusercontent.com/12032241/230263301-11887a77-b898-4f84-862a-5e647f6695de.png)
IP_ 192.168.1.111_ 222_ The 234 device does not have any monitoring data and does not have a function key to display the topology map

**Comment by dudumao520** [comment]
Hello, I have enabled the SNMP timing database and it can be displayed normally, but the IP address_ 192.168.1.111_ 222_ 234 device does not have any monitoring data and does not have a function key to display the topology map
![112](https://user-images.githubusercontent.com/12032241/230263787-46673877-dc32-4e92-8995-89f93a9123f3.png)
I don't understand, IP_ 120 devices and IP_ 111_ 222 has the same operating system version and SNMP configuration, why is IP_ 120 devices can see interface related data and device operation data？

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520 we pushed an other update with other debug print to understand which polling is failing/missing.
Like the last time, run:

redis-cli SET "ntopng.debug.print_snmp_debug" 1

Wait for 10 minutes more or less and then run

redis-cli DEL 'ntopng.debug.print_snmp_debug'

and send me the output.
The output should have all the information polled from those servers and their value, in this way we can probably (hopefully) understand what's happening

**Comment by dudumao520** [comment]
[ntop-0407.log](https://github.com/ntop/ntopng/files/11179333/ntop-0407.log)

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520 (you do not need to update) please run:

redis-cli SET "ntopng.debug.print_snmp" 1

Wait for 10 minutes more or less and then run

redis-cli DEL 'ntopng.debug.print_snmp'

and send me the output again.
It's an other debug print

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520 any news about the debug print?

**Comment by lucaderi** [comment]
Closing for inactivity
