### ISSUE TITLE
SNMP Page is not opening its showing error

### ISSUE THREAD

**Issue by SHBIL** [ntop/ntopng#7985]
**Environment**:
OS name: [Ubuntu]
OS version: [ 20.04]
Architecture: [amd64]
*ntopng Enterprise M v.6.0.231101 (Ubuntu 20.04.6 LTS)

@ntopng:~$ ntopng --version
Version:        6.0.231101 [Enterprise/Professional build]
GIT rev:        6.0-stable:c57c9b2f273e8d8118a47b6a5bbfee6cd9eed6b5:20231101
Pro rev:        r6146
Built on:       Ubuntu 20.04.6 LTS
System Id:      L3BFD4B6C5505621F--U3BFD4B6C88713DEA--OL
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Sat Sep 14 21:50:21 2024 [313 days left]
License:        a0SWe43vKP0KwEhwyXaHhVmkuGCaenk1YeNlUit2txthLovxa5myvMbba3J1B/wd3ccAq
                6AEjZ9oay9bbREk9KqrUAVRRXbjSiQK+nyjTtvLK2tQzbtSIv67rtvoCQAnwfa7DvZGwf
                tBqeDI5bm+lMxai6+kxmKw1iNliJtMLM6+Hr9DvwVVuK1TuKAHivvtsj6rYr87/1euWVM
                GKns8HPnjSGXQC8r/b7dVNbCi+eFTggepjAxwbvol9eE/wiAEtIhCYgMv6Z0RJO1/7WXb

**What happened**:

**How did you reproduce it?**

**Debug Information**:

**Comment by SHBIL** [comment]
![ntop snmp](https://github.com/ntop/ntopng/assets/109748815/bb43f76a-deb1-4795-9de7-4f4526b0a3ce)

**Comment by NicoMaio** [comment]
Hi @k-shehzad,

could you please send to maio@ntop.org the results of `redis-cli GET "ntopng.prefs.snmp_configuration"` and `redis-cli GET "ntopng.cache.snmp_configuration_stats"`?

**Comment by SHBIL** [comment]
Hi @NicoMaio i have sent the results over the email, pls have it check, TU

**Comment by NicoMaio** [comment]
Fixed in pro repo by 844fbada0b6b8c2694270f8e4eafe1b991d3a5c5

**Comment by NicoMaio** [comment]
Hi @SHBIL,
the stable version with the fix should be ready within a couple of hours.

**Comment by SHBIL** [comment]
Hi @NicoMaio we are ready to test, how can i upgrade  the fix ?

**Comment by NicoMaio** [comment]
Hi @SHBIL,
If you have already executed 'apt-get update,' please proceed to restart the ntopng service, as the fix should now be ready for testing.
If you haven't updated it using the command line, it's also possible to do so through the GUI by accessing the top right menu, represented by the icon with a man.

**Comment by SHBIL** [comment]
Hi @NicoMaio i have updated using the  'apt-get update,' and restarted the ntopng services, but still facing the same issue,

**Comment by NicoMaio** [comment]
@SHBIL  Could you please send me the current screen of the error again to [maio@ntop.org](mailto:maio@ntop.org)?

**Comment by SHBIL** [comment]
@NicoMaio i have sent it pls have it check

**Comment by MatteoBiscosi** [comment]
Verified as fixed
