### ISSUE TITLE
Daily Traffic Report uses Custom option which does not exist

### ISSUE THREAD

**Issue by dkggpeters** [ntop/ntopng#8208]
**Environment**:
* OS name: FreeBSD (PFSense 23.09.1)
* OS version: 14.0
* Architecture: amd64
* ntopng version/revision: 6.1.240207

**What happened**:
Setup daily reports and when the link is followed to the Dashboard Traffic Reports the report option goes to "Custom" which does not exist.

Report from email link:

![image](https://github.com/ntop/ntopng/assets/63671969/fbb6ab4d-f5eb-49b5-9097-4334570983bb)

Dashboard -> Traffic Reports current report options

![image](https://github.com/ntop/ntopng/assets/63671969/d71b854c-55a5-4050-89bd-d5fabbb43936)

**Comment by MatteoBiscosi** [comment]
Hi @dkggpeters could you please share the link you received from the mail and the link you of the ntopng working?

**Comment by dkggpeters** [comment]
Link for daily report

http://dkggpeters.com:3000/lua/pro/reportng.lua?ifid=1&report_name=auto-2024-Feb-11-1707714043&epoch_begin=1707627643&epoch_end=1707714043

Link that works using Default reports

http://dkggpeters.com:3000/lua/pro/reportng.lua?ifid=1&epoch_begin=1707627600&epoch_end=1707714000&report_template=default

**Comment by dkggpeters** [comment]
I did a test report using the same date and time parameters midnight to midnight and all works fine when pulling it up.

http://10.57.1.1:3000/lua/pro/reportng.lua?ifid=1&epoch_begin=1707627600&epoch_end=1707714000&report_name=test

![image](https://github.com/ntop/ntopng/assets/63671969/29e47b56-ba9b-41b0-b73d-7fba63706e49)

**Comment by NicoMaio** [comment]
Hi @dkggpeters,

We have pushed a fix for this issue, which will be included in the next daily build. 
Please update and let us know if everything is alright.

**Comment by dkggpeters** [comment]
@NicoMaio Auto Reports are no longer being generated and settings are on in Settings and by Interface.  The last one I have is 2/24/2024

I am now on version 6.1.240305 (FreeBSD 14.0)

![image](https://github.com/ntop/ntopng/assets/63671969/44e4d52b-2861-4b77-8bfd-2fdf3f89e8af)

**Comment by NicoMaio** [comment]
@dkggpeters I have set up ntopng to reproduce the potential issue. I will provide an
update on it tomorrow.

**Comment by NicoMaio** [comment]
Hi @dkggpeters , 
I tried to reproduce this issue but received the daily reports correctly. 
Please update to the latest version and let me know tomorrow.

**Comment by dkggpeters** [comment]
Still not working for me even on 6.1.240318.  I am noticing that any time based activities stopped working aroung the same time including active monitoring and configuration backups.

**Comment by NicoMaio** [comment]
Hi @dkggpeters,

Just to confirm, have you enabled the 'Daily Reports Generation' flag in Preferences -> Reports Tab?
![image](https://github.com/ntop/ntopng/assets/55502486/1867bed4-0098-4b8f-8ff5-108a17723418)

**Comment by dkggpeters** [comment]
Yes it is set to on:

![image](https://github.com/ntop/ntopng/assets/63671969/6d8c9fe9-6b27-4235-b66a-e3e48d4d4dc6)

![image](https://github.com/ntop/ntopng/assets/63671969/fc8ae1e4-d4cf-43d9-b5d5-2c18bbec62a4)

It appears that anything time based related as active monitoring stopped working as well.

I just update to version 6.1.240422 to see if that works.

**Comment by dkggpeters** [comment]
Network Discovery does work using the the interval which I have set to 6 hours.

**Comment by NicoMaio** [comment]
Hi @dkggpeters, are you using the community version of ntopng?

**Comment by dkggpeters** [comment]
I am using Enteriprise.

**Comment by NicoMaio** [comment]
@dkggpeters is it an Enterprise L license?

**Comment by NicoMaio** [comment]
Hi @dkggpeters, a new version of ntopng should be ready. 
This latest version includes more logs to debug your case. To enable them please run this command from the terminal `redis-cli SET "ntopng.prefs.automatic_reports_debug_enabled" "1"`.
Then please provide us the logs of ntopng after some days to see what's going on in the daily script that makes the daily report.

**Comment by MatteoBiscosi** [comment]
Closing for inactivity, please reopen if needed
