### ISSUE TITLE
Counter overflow

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8364]
apr 27 12:47:34 ntop2 ntopng[15572]: 27/Apr/2024 12:47:34 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow
apr 27 12:47:43 ntop2 ntopng[15572]: 27/Apr/2024 12:47:43 [NetworkInterface.cpp:11118] WARNING: Internal Error (3): Counter overflow

**Comment by MatteoBiscosi** [comment]
I was not able to reproduce this issue, however, checking the code, it was possible that the same host entered multiple times in the set_hash_entry_state_idle and exited, causing multiple times the decrease of the counter.
Moving the decrease to the destroyer of the class should fix the issue (the increase is inside the constructor)

**Comment by lucaderi** [comment]
At the moment the problem does not show up anymore on hsol. Closing it for now, reopening if necessry

**Comment by lucaderi** [comment]
Still broken

May  8 07:36:30 ntop2 ntopng: 08/May/2024 07:36:30 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:36:30 ntop2 ntopng[9749]: 08/May/2024 07:36:30 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng[9749]: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng[9749]: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng[9749]: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng[9749]: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng[9749]: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow
May  8 07:39:25 ntop2 ntopng: 08/May/2024 07:39:25 [NetworkInterface.cpp:11073] WARNING: Internal Error (3): Counter overflow

**Comment by MatteoBiscosi** [comment]
After the latest update the issue seems fixed (hsol), in case the issue is back please reopen the ticket
![image](https://github.com/ntop/ntopng/assets/49585191/53e7a5cd-1acc-4e06-b3a3-c9dcb2515ef8)

**Comment by MatteoBiscosi** [comment]
Moreover, removed counter increase/decrease during shutdown, being a useless work due to the fact that those info are not saved during shutdown nor used for future activities
