### ISSUE TITLE
Can we please have hostnames in the "Top Local Hosts" widget (and not IP addresses)

### ISSUE THREAD

**Issue by tescophil** [ntop/ntopng#8994]
Simple enough, hostnames are used all over the interface, apart from the main dashboard "Top Hosts (Local)" widget which uses IP's.. can we _please_ charge this to hostnames so it's actually useful ?

![Image](https://github.com/user-attachments/assets/e4063ae9-e455-4439-ab27-4978106b4f97)

**Comment by MatteoBiscosi** [comment]
Hi @tescophil the issue should now be fixed, in tomorrow update you should have the fix on

**Comment by tescophil** [comment]
Hi, 

Looks good, however I'm now seeing non local hosts on the widget which I didn't notice before (I have all my local subnets defined so don't see why this Google IP address would be classified as a local host) 

![Image](https://github.com/user-attachments/assets/06e3d924-744b-46b1-84db-400c1f3cd47e)

**Comment by MatteoBiscosi** [comment]
It's name is "google-hub" so probably it's an IOT device (alexa, TV or something like that). Please check the Host by searching for that name

**Comment by tescophil** [comment]
![Image](https://github.com/user-attachments/assets/0d357dc1-4086-468f-b8da-edcd4b509586)

Still seeing Remote IP's listed in the Top Hosts (Local)

23.73.136.88 is not a Local Host:

![Image](https://github.com/user-attachments/assets/390ff2b3-30ee-4554-bcff-eae950b08b30)

**Comment by DGabri** [comment]
Hi there, this is fixed in the latest version, displayed hosts on the pie chart are both local and remote, there was an issue in the title. Thanks for pointing this out!

<img width="1042" alt="Image" src="https://github.com/user-attachments/assets/95a0a203-de1b-49fb-9e4c-cfedd8bd8567" />
