### ISSUE TITLE
/lua/if_stats.lua bug(2.5.170215)

### ISSUE THREAD

**Issue by ArchyCho** [ntop/ntopng#988]
Version	2.5.170215 - Pro Small Business Edition
Built on	Debian GNU/Linux 8.2 (jessie)
nDPI	1.8.0-dev-692-b35c1ab
 Twitter Bootstrap	3.x
 Font Awesome	4.x
RRDtool	1.4.8
Redis Server	2.8.17
Mongoose web server	3.7
LuaJIT	LuaJIT 2.0.3
ØMQ	4.0.5
GeoIP	1.6.2 
 
This product includes GeoLite data created by MaxMind.
Data-Driven Documents (d3js)	2.9.1 / 3.0

The page could only show the counting of 1H ,
even I click for 1M or 1Y , it still shown the count of 1H (default)

**Comment by emanuele-f** [comment]
Hi, this is already fixed with 7f48b1b4ad55c1ade4323cf76ceed5a0f768f4dd. Please update

**Comment by ArchyCho** [comment]
Dear Team

Please send me the update procedure , thanks.

ArchyCho

**Comment by ArchyCho** [comment]
Dear Team

Sorry for stupid question , please ignore.

I have update the scripts and working correctly now.

Archy Cho

**Comment by ArchyCho** [comment]
After updated , the host_details.lua still shown 1H only , please check.

**Comment by emanuele-f** [comment]
Thank you for reporting. I've made a fix commit ff1568a4ef191f517048e29665d4a94478338654. New packages will be available tomorrow.
